# SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
#
# SPDX-License-Identifier: MIT

# Auto-generated by generate-deps.sh — do not edit

$(FETCH_PATH)/.i2p.2.13.0.stamp: .container/user/deps/i2p/url.deps .container/user/deps/i2p/version.deps
	M6E_DEPS_STAGE=user .makefile/container/scripts/fetch.sh i2p
	touch $@

.container/user/deps/i2p/hash.deps: $(FETCH_PATH)/.i2p.2.13.0.stamp
	M6E_DEPS_STAGE=user .makefile/container/scripts/update-hash.sh i2p

PREREQUISITES += .container/user/deps/i2p/hash.deps

